### ISSUE TITLE
Use entity meta-data (tags / labels) to provide the overview orchestration

### ISSUE THREAD

**Issue by ricegi** [newrelic/nr1-slo-r#49]
## Summary

On shipping SLO/R relies on a construct of an SLO Group (nee organization nee team) to group multiple SLOs into one attainment. This is adding an artificial construct that won't age well in New Relic - so it would be better to use the meta-data that is already available with the entities as the basis for grouping. NR users can then just worry about organizing their entities with proper taxonomy instead of having to re-do it in SLO/R. 

## Desired Behaviour

Select from a list of available metadata or being typing the metadata and you get an overview report for all the SLOs on all the entities that contains that metadata. We could allow for multiple tags narrowing the context.

## Possible Solution

update the composite / organization query logic to take an array of applicable entities based on the various tags chosen. 

## Additional context

I think this would dramatically improve the flexibility to report overviews for SLOs.

**Comment by norbertsuski** [comment]
@tangollama @ricegi our understanding is that user can create new SLO (still in context of selected entity, so still SLO will be created per entity?), but instead of adding it to any group, can add it to specific tag/metadata that exists in the entity. 

And then - in SLO Overview window, user can select available metadata/tags and show created SLOs?

Should user be able to create SLOs with both group and metadata/tags or only either of them?

**Comment by tangollama** [comment]
@norbertsuski yes. The long-term objective is to age-out SLO Group in favor of tag; but the objective here would be to support one or the other - not both in the same SLO.

**Comment by ricegi** [comment]
That correct - since the SLO documents are directly related to an entity we wanted to create a UI that would allow users to search for tags - and then we would aggregate all SLOs on entities with those tags. Like the way the filtering capability works for Distributed Traces.
