### ISSUE TITLE
SLO/R Overview shows no SLOs defined, even though several are created

### ISSUE THREAD

**Issue by jdmchone** [newrelic/nr1-slo-r#52]
SLO/R Overview shows no SLOs defined, even though several are created

## Description

When I launch the SLO/R Overview page, it shows now SLOs defined. The SLO Group dropdowns are empty, even though several SLOs and Groups have been created in NR1. 

## Steps to Reproduce

1 - Go to a service and define a new Errors SLO
2 - Name the group while defining the SLO
3 - Go the main NR1 page, and click on the SLO/R Launcher
4 - No SLOs are showing

## Expected Behaviour

Defined SLOs should show in the SLO/R Overview page.

* NR1 CLI version used: 1.10.10 darwin-x64 node-v10.16.3
* Browser name and version: Chrome
* Operating System and version: MacOS

## Additional Attachments

![image](https://user-images.githubusercontent.com/2171698/72009105-386af800-3223-11ea-86a9-e88ad3eb70ba.png)

![image](https://user-images.githubusercontent.com/2171698/72009003-022d7880-3223-11ea-89b4-725d9de2f239.png)

**Comment by ricegi** [comment]
thanks @jdmchone - looking into this right now!

**Comment by ricegi** [comment]
@jdmchone - I haven't been able to reproduce this - and I think it might have something to do with the SLO document schema version issue another user has reported. 

If that is the case updating to the latest SLO/R codebase and deleting re-adding the SLO documents should solve the problem - but that's a less than acceptable long term workaround!

If you could post the SLO definition JSON (with account ID and account name omitted) that would help me confirm my suspicion.  In the meantime I am going to work to mitigate the issue. 

If you prefer to send the document directly to me rather than post please do so via email at gil@newrelic.com

Thank-you again for reporting this issue and sorry for the speedbump here!

**Comment by jdmchone** [comment]
Updating to the latest codebase 1.4.4 did not work, as I had already been using the latest. Which SLO definition are you referring to?

**Comment by devfreddy** [comment]
@jdmchone ricegi is referring to the JSON format for the definition of an SLO. We made some modifications shortly after release that could affect the UI's ability to aggregate/display them, though we've been unable to replicate it.

If it's related to this document definition, deleting them all and recreating should resolve the issue but before we go removing all of your hard work - we'd love to get a little diagnostic information on what you're experiencing.

Could you open up "Inspect" in the browser of your choice and look in the console for any errors? If you see any please copy/share/screenshot as much information as you can.

**Comment by ricegi** [comment]
Finally fixed- thx for all the patience on this one. This was due to the way we were scanning entities with SLOs defined. Doing it in a real inefficient way that led to timeouts. Now we know! This is also going to help us in using tags as the aggregating functions for SLOs --- new release coming soon!
