### ISSUE TITLE
NRQL query for alert based SLO not correct

### ISSUE THREAD

**Issue by jeffrey-hines** [newrelic/nr1-slo-r#53]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

After defining SLO it doesn't work. When viewing the details of the SLO the NRQL has WHERE policy_name IN (’’) which obviously won't work.

## Steps to Reproduce

Define a SLO

## Expected Behaviour

Should generate the correct NRQL.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: @datanerd/nr1/1.2.2 win32-x64 node-v10.16.3
* Browser name and version: Chrome
* Operating System and version: Windows 10

## Additional context

[TIP]:  # ( Add any other context about the problem here. )
![image](https://user-images.githubusercontent.com/59659186/72005021-3e0c1200-3212-11ea-9ef2-592d539ea0ec.png)

**Comment by ricegi** [comment]
@jeffrey-hines - sorry in the delay in getting this reviewed. It looks like we made a change in the array implementation of the alerts - adding an array of objects rather than a simple array of string Alert names. The result when you click on the info button is to not recognize the simple array and show a blank. 

To fix you would need to delete the defined SLO document and recreate it. The latest version of SLO/R should use the correct model and implement it correctly.

I am going to review the consistency of the embedded arrays in the SLO document to - since it is a versioned schema we should be able to understand what schema we're loading and make the appropriate modifications the SLO and resave in a new version. I think we missed the opportunity to code that check before we shipped.      

If there is any chance you could check that the "slo_r_version": is "1.0.1", I would appreciate it - it seems that version wasn't rev'ed when the change to including an object was made. 

And thank you for reporting this issue - I'll update the community thread to point to this bug report.

**Comment by ricegi** [comment]
thank you Jeff - I think this is the root of the issue.

**Comment by ricegi** [comment]
Should be addressed with rel 1.4.6
