### ISSUE TITLE
Unable to publish the nerdlet after cloning

### ISSUE THREAD

**Issue by siva-epari** [newrelic/nr1-slo-r#70]
Unable to publish the nerdlet after a fresh clone of the master branch

## Description

When i clone the repo & publish it, it throws following error:
`✖  Error: Bad request; please make sure a Nerdpack file(tar.gz) is present.`

## Steps to Reproduce

```shell
$ nr1 nerdpack:clone -r https://github.com/newrelic/nr1-slo-r.git
$ cd nr1-slo-r/
$ nr1 nerdpack:uuid -g
$ nr1 nerdpack:publish
```
## Expected Behaviour

To publish the nerdlet, when `nr1 nerdpack:publish` is executed

## Relevant Logs / Console output

```shell
Sivas-MacBook-Pro:~ siva$ nr1 nerdpack:clone -r https://github.com/newrelic/nr1-slo-r.git
Cloning repository...
Cloning into '/Users/siva/nr1-slo-r'...
remote: Enumerating objects: 143, done.
remote: Counting objects: 100% (143/143), done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 1722 (delta 64), reused 87 (delta 26), pack-reused 1579
Receiving objects: 100% (1722/1722), 3.32 MiB | 2.49 MiB/s, done.
Resolving deltas: 100% (960/960), done.
Setting repo as remote upstream...
Installing dependencies...
Re-generating UUID...
Committing new UUID...

 ✔  The Nerdpack has been successfully cloned!

To start this project run:
 ⁎  cd nr1-slo-r
 ⁎  nr1 nerdpack:serve

Sivas-MacBook-Pro:~ siva$ cd nr1-slo-r/
Sivas-MacBook-Pro:nr1-slo-r siva$ nr1 nerdpack:uuid -g
✔ UUID already exists. Do you want to overwrite it? … yes

The new generated id is 9a5f6532-ebae-4ad8-8e4d-27b277b74f9d
Sivas-MacBook-Pro:nr1-slo-r siva$ 
Sivas-MacBook-Pro:nr1-slo-r siva$ nr1 nerdpack:publish
Found and loaded 4 nr1.json files on nr1-slo-r (9a5f6532-ebae-4ad8-8e4d-27b277b74f9d) Nerdpack.

Nerdpack:
 ✔  nr1-slo-r (9a5f6532-ebae-4ad8-8e4d-27b277b74f9d) nr1.json

Launchers:
 ✔  nr1-slo-r-launcher launchers/nr1-csg-slo-r-launcher/nr1.json

Nerdlets:
 ✔  nr1-slo-r-nerdlet nerdlets/nr1-csg-slo-r-nerdlet/nr1.json
 ✔  slo-r-main nerdlets/slo-r-main/nr1.json
 ✔  slo-r-entity nerdlets/slo-r-entity/nr1.json

🛠  Built artifact files for:
 ⁎  9a5f6532-ebae-4ad8-8e4d-27b277b74f9d--nr1-slo-r-nerdlet built ✔
 ⁎  9a5f6532-ebae-4ad8-8e4d-27b277b74f9d--slo-r-main built ✔
 ⁎  9a5f6532-ebae-4ad8-8e4d-27b277b74f9d--slo-r-entity built ✔

 ✔  Nerdpack built successfully!

Publishing Nerdpack nr1-slo-r (9a5f6532-ebae-4ad8-8e4d-27b277b74f9d)
✖  Error: Bad request; please make sure a Nerdpack file(tar.gz) is present.

ℹ  You can run this command with "--verbose" for more info.
```

## Your Environment

* NR1 CLI version used: @datanerd/nr1/1.19.3 darwin-x64 node-v10.16.3
* node: v12.14.0
* Browser name and version: Chrome Version 80.0.3987.116 (Official Build) (64-bit)
* Operating System and version: macOS mojave 10.14.6

**Comment by devfreddy** [comment]
@siva-epari Thanks for reporting this. We're looking into it. I've been able to replicate and might have also found a workaround.

If you're able, could you try the following steps:

- `nr1 profiles:list`
- Copy the name of the profile labeled `(default)`
- Run `nr1 nerdpack:publish --profile=<name of your profile>`

For example, if my current default profile is "demo-profile-1", previously I would have run something like:
`nr1 nerdpack:publish`

This would utilize the default profile automatically, but is now instead throwing an error. Changing this to: `nr1 nerdpack:publish --profile=demo-profile-1`
has allowed me to successfully publish.

Please report back if this resolves your issue, meanwhile we'll be investigating root cause and a bugfix. Thanks!

**Comment by doesterr** [comment]
I'm running into the same issue.

I'm getting either
`✖  Error: Bad request; please make sure a Nerdpack file(tar.gz) is present.`
or
`✖  Error: Nerdpack with id: 4380103d-eb2f-4465-80df-98cd6dbe9597 and AccessInfo(packageType=CUSTOMER, environment=production, accountId=<snip>, userId=<snip>) doesn't exist`

when running `nr1 nerdpack:publish`

I've tried it with the `--profile` option as well as @devfreddy suggested above, but it doesn't make a difference for me. 



I'm using the latest nr1 CLI: `@datanerd/nr1/1.19.5 darwin-x64 node-v10.16.3`

**Comment by devfreddy** [comment]
@doesterr Thanks for reporting. Some of us can reproduce this but others can't, so any additional information you can provide would be super helpful.

I just played around with this locally, and noticed a few different things:

- In an attempt to find out more information, I ran `nr1 nerdpack:publish --verbose`  instead of simply `nr1 nerdpack:publish`, and could not reproduce it with the `--verbose` command, perhaps you could try that as well

- Running `nr1 nerdpack:publish` a second time after it fails the first time, yields a successful run, I'd love to hear if that's the case for you as well

- I am unable to reproduce this on all of our apps, have you tried any of the others, such as https://github.com/newrelic/nr1-top ?

We're working with the team responsible for the CLI and will report back as we sort this out.

**Comment by doesterr** [comment]
@devfreddy thanks for coming back to me.

- Using the --verbose flag doesn't make a difference. I'm still getting either of the errors mentioned in my previous comment

- I ran the publish command multiple times, never successful. The only thing that changes it that sometimes the error messages alternate from one run to the next

- I've deployed a couple of your apps successfully before (I also had a previous version of slo-r deployed, but I can't get the new version out). I just tried it with nr1-top for the first time, and could successfully publish it.

**Comment by doesterr** [comment]
I just ran `nr1 nerdpack:uuid -g` before giving it another try.
This re-created the UUID, and I could publish it successfully afterwards.

This is solved for me. Thanks!

**Comment by psychohamster** [comment]
I was experiencing the same issue on a different nerdpack, and even though I had regenerated the uuid earlier in the dev cycle, doing it again seemed to solve the problem. Thanks for posting @doesterr - saved me hours!

**Comment by tangollama** [comment]
@siva-epari is this still an issue for you?
